# Generated by Django 5.1 on 2024-12-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_completed_exercises_profile_last_active_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fluency_level',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='grammar_level',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pronunciation_level',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='vocabulary_level',
            field=models.JSONField(default=dict),
        ),
    ]
