# Generated by Django 5.1 on 2024-12-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_age_profile_first_name_profile_fluency_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fluency_level',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grammar_level',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronunciation_level',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vocabulary_level',
            field=models.JSONField(),
        ),
    ]
