services:
  # PostgreSQL Database
  db:
    image: postgres:16.3
    container_name: ai-english-postgres-db
    environment:
      POSTGRES_DB: ai_english
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis (for Celery)
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  # Django Backend
  backend:
    build: ./backend
    container_name: django-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=english_learning_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  # Celery Worker
  celery:
    build: ./backend
    container_name: celery-worker
    command: celery -A your_project_name worker --loglevel=info
    environment:
      - POSTGRES_DB=ai_english
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - backend
      - redis

  # React Frontend
  frontend:
    build: ./frontend
    container_name: react-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data: