
export interface testimonials {
    id: number,
    firstName: string,
    lastName: string,
    role: string,
    text: string,
    rating: number
}

const data: testimonials[] = [
    { id: 1, firstName: 'Michael', lastName: 'Johnson', role: 'CEO', rating: 5, text:"This platform is amazing for IELTS preparation! The practice tests are very similar to the actual exam, and the personalized feedback helped me identify and work on my weak areas. The targeted lessons were tailored to my needs, focusing on the skills I needed to improve the most. I was able to boost my band score by 2 points within just a few months. The convenience of studying anytime, anywhere was a huge plus for me as well. Highly recommend this to anyone preparing for IELTS!" },
    { id: 2, firstName: 'Emily ', lastName: 'Smith', role: 'Product Designer', rating: 4.6, text:"This platform has everything you need to excel in English, whether it’s for academic purposes or professional development. The combination of IELTS preparation, job interview practice, and personalized learning paths is perfect. The real-time feedback helps you learn and improve quickly. I’ve used other language learning platforms before, but none have been as comprehensive and effective as this one. The convenience of being able to study whenever and wherever I want is just the cherry on top. Highly recommend!" },
    { id: 3, firstName: 'James ', lastName: 'Brown', role: 'Manager', rating: 4.9, text:"The job interview practice feature is a game-changer. The AI-powered mock interviews were incredibly realistic and gave me a good sense of what to expect. The personalized feedback on my responses was extremely valuable, highlighting areas where I could improve. The expert tips and confidence-building exercises made a huge difference. When it came time for my actual interview, I felt well-prepared and confident, and I successfully landed my dream job! This platform truly made a difference in my career." },
    { id: 4, firstName: 'Olivia ', lastName: 'Williams', role: 'Software Engineer', rating: 4.7, text:"I love how the platform creates customized learning paths based on my specific goals. Whether I’m focusing on improving my IELTS score or preparing for a job interview, the study plans are tailored to my needs and keep me on track. The progress tracking feature is also fantastic—it’s motivating to see my improvements over time. The interactive exercises and real-time feedback make learning engaging and effective. This platform has transformed the way I study English."},
    { id: 5, firstName: 'Daniel ', lastName: 'Davis', role: 'Copywriter', rating: 5, text:"As someone who struggles with speaking English, the real-time feedback feature on this platform has been incredibly helpful. The AI provides immediate corrections and suggestions, which has greatly improved my pronunciation and fluency. The job interview practice sessions boosted my confidence and prepared me for a variety of question. I recently went through an interview process and felt much more prepared and confident thanks to this platform. It’s been a valuable resource in my language learning journey." },
    { id: 6, firstName: 'Sophia ', lastName: 'Miller', role: 'Marketing', rating: 4.4, text:"I was skeptical about using an online platform for job interview preparation, but this one exceeded my expectations. The mock interviews felt like real interviews, and the feedback was incredibly detailed and constructive. The platform also provided excellent resources on how to answer common interview question and how to present myself professionally. I walked into my job interview feeling prepared and confident, and I got the job! This platform is an excellent investment for anyone looking to advance their career." },
    { id: 7, firstName: 'Kate', lastName: 'Brown', role: 'Graphic Designer', rating: 4.2, text:"Overall, this English AI platform is quite impressive. The AI provides accurate and helpful feedback, and the exercises are very engaging. I did experience a few minor glitches, but they didn't significantly affect my learning experience. With a bit of fine-tuning, it could easily be a 5-star tool." },
];

export default data;