# Generated by Django 5.1 on 2024-11-06 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL', 'Fill in the Blank'), ('MATCH', 'Matching'), ('COMPLETE', 'Sentence Completion'), ('WRITING', 'Writing')], max_length=10)),
                ('question_text', models.TextField()),
                ('choices', models.JSONField(blank=True, null=True)),
                ('answer', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField(default=1)),
                ('last_served_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
