# Generated by Django 5.1 on 2024-11-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0002_delete_question_delete_userquizscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL', 'Fill in the Blank'), ('MATCH', 'Synonym/Antonym Matching'), ('COMPLETE', 'Sentence Completion'), ('WRITING', 'Writing'), ('OPENWRITING', ' Open-Ended Writing')], max_length=20)),
                ('question_text', models.TextField()),
                ('choices', models.JSONField(blank=True, null=True)),
                ('answer', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField(default=1)),
                ('last_served_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
