# Generated by Django 5.1 on 2024-11-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL', 'Fill in the Blank'), ('MATCH', 'Synonym/Antonym Matching'), ('COMPLETE', 'Sentence Completion')], max_length=20)),
                ('question_text', models.TextField()),
                ('choices', models.JSONField(blank=True, null=True)),
                ('answer', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField(default=1)),
                ('last_served_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
