# Generated by Django 5.1 on 2024-11-07 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_vocabquestion_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabquestion',
            name='last_served_date',
        ),
    ]
