# Generated by Django 5.1 on 2024-11-08 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_vocabquestion_last_served_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VocabQuestion',
        ),
    ]
