# Generated by Django 5.1 on 2024-11-09 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_category_unique_together_subtopiccategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopiccategory',
            name='exercise_name',
        ),
    ]
