# Generated by Django 5.1 on 2024-11-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_subtopiccategory_exercise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_hybrid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_quiz',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
