# Generated by Django 5.1 on 2024-11-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_category_is_hybrid_remove_category_is_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenEnded',
            new_name='OpenEndedQuestion',
        ),
    ]
