# Generated by Django 5.1 on 2024-11-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_rename_openended_openendedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='time_duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
