# Generated by Django 5.1 on 2024-11-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_multiplechoicequestion_time_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='time_duration',
        ),
    ]
