# Generated by Django 5.1 on 2024-12-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_remove_multiplechoicequestion_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='difficulty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='openendedquestion',
            name='difficulty',
            field=models.IntegerField(),
        ),
    ]
