# Generated by Django 5.1 on 2024-11-18 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('last_score', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('last_attempt_date', models.DateTimeField(auto_now=True)),
                ('max_score', models.IntegerField(default=0)),
                ('quiz_topic', models.CharField(blank=True, max_length=50, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('speaking_time', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
