# Generated by Django 5.1 on 2024-11-06 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_duration', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('sentence_count', models.IntegerField()),
                ('vocab_score', models.IntegerField()),
                ('sentence_structure_score', models.IntegerField()),
                ('readability_score', models.IntegerField()),
                ('grammar_score', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('unique_words', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
