# Generated by Django 5.1 on 2024-12-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech_analysis', '0003_alter_speechanalysis_audio_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpeechAnalysis',
        ),
    ]
