name: Python Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      image: postgres:16
      env:
        POSTGRES_USER: ${{ secrets.DATABASE_USER }}
        POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        POSTGRES_DB: ai_english
      ports:
        5432:5432
      options: >-
        --health-cmd "pg_isready -U ${{ secrets.DATABASE_USER }}" 
        --health-interval 10s 
        --health-timeout 5s 
        --health-retries 5

    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.5

    - name: Install/Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Dependencies
      run: pip install -r requirements.txt
        
    - name: Run Tests
      env:
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

      run: python manage.py test tests
