name: Python Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_USER: test_user
      DATABASE_PASSWORD: test_password
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: ai_english
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.5

      - name: Install/Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        env:
          DATABASE_USER: test_user
          DATABASE_PASSWORD: test_password
          EMAIL_HOST_USER: ${{ env.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ env.EMAIL_HOST_PASSWORD }}
        run: python manage.py test tests
